[2025-01-08T12:53:53.218+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-01-08T12:53:53.232+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-01-08T12:53:53.233+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T12:53:53.256+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-04 00:00:00+00:00
[2025-01-08T12:53:53.269+0000] {standard_task_runner.py:57} INFO - Started process 214 to run task
[2025-01-08T12:53:53.281+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-04T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp82iycsc7']
[2025-01-08T12:53:53.291+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask unpack_to_raw
[2025-01-08T12:53:53.362+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T12:53:53.520+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-04T00:00:00+00:00 [running]> on host 1b6611c57a45
[2025-01-08T12:53:53.939+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-04T00:00:00+00:00'
[2025-01-08T12:53:53.962+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T12:53:53.965+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-08T12:53:53.985+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T12:53:54.525+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-08T12:53:54.527+0000] {subprocess.py:93} INFO -   File "/opt/***/build/unpack_to_raw.py", line 3, in <module>
[2025-01-08T12:53:54.530+0000] {subprocess.py:93} INFO -     from datasets import load_dataset
[2025-01-08T12:53:54.535+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'datasets'
[2025-01-08T12:53:54.536+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-08T12:53:54.568+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-08T12:53:54.579+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250104T000000, start_date=20250108T125353, end_date=20250108T125354
[2025-01-08T12:53:54.639+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task unpack_to_raw (Bash command failed. The command returned a non-zero exit code 1.; 214)
[2025-01-08T12:53:54.691+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-08T12:53:54.781+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-08T13:31:24.700+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-01-08T13:31:24.707+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-01-08T13:31:24.707+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T13:31:24.716+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-04 00:00:00+00:00
[2025-01-08T13:31:24.719+0000] {standard_task_runner.py:57} INFO - Started process 345 to run task
[2025-01-08T13:31:24.723+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-04T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpo5cpawxf']
[2025-01-08T13:31:24.725+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask unpack_to_raw
[2025-01-08T13:31:24.736+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T13:31:24.764+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-04T00:00:00+00:00 [running]> on host 8105279881a3
[2025-01-08T13:31:24.814+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-04T00:00:00+00:00'
[2025-01-08T13:31:24.822+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T13:31:24.822+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-08T13:31:24.829+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T13:31:35.880+0000] {subprocess.py:93} INFO - Téléchargement des données...
[2025-01-08T13:31:35.885+0000] {subprocess.py:93} INFO - Données téléchargées et organisées.
[2025-01-08T13:31:35.885+0000] {subprocess.py:93} INFO - Combinaison et téléversement des fichiers...
[2025-01-08T13:31:35.885+0000] {subprocess.py:93} INFO - Erreur lors du téléversement : Unable to locate credentials
[2025-01-08T13:31:35.886+0000] {subprocess.py:93} INFO - Traitement terminé.
[2025-01-08T13:31:36.045+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-08T13:31:36.097+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250104T000000, start_date=20250108T133124, end_date=20250108T133136
[2025-01-08T13:31:36.134+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-08T13:31:36.166+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
