[2025-01-15T15:33:28.817+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-01-15T15:33:29.284+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-01-15T15:33:29.285+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-15T15:33:29.421+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-04 00:00:00+00:00
[2025-01-15T15:33:29.597+0000] {standard_task_runner.py:57} INFO - Started process 238 to run task
[2025-01-15T15:33:29.733+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-04T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/wikitext_dag.py', '--cfg-path', '/tmp/tmpeu8lss67']
[2025-01-15T15:33:29.921+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask unpack_to_raw
[2025-01-15T15:33:30.196+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-15T15:33:31.379+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-04T00:00:00+00:00 [running]> on host 9159fb56fd7e
[2025-01-15T15:33:42.496+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-04T00:00:00+00:00'
[2025-01-15T15:33:42.683+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-15T15:33:42.731+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-15T15:33:42.904+0000] {subprocess.py:86} INFO - Output:
[2025-01-15T15:34:29.926+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2025-01-15T15:34:30.483+0000] {process_utils.py:131} INFO - Sending 15 to group 238. PIDs of all processes in the group: [246, 238]
[2025-01-15T15:34:30.569+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 238
[2025-01-15T15:34:31.461+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-15T15:34:32.460+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-01-15T15:34:33.162+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-01-15T15:34:33.493+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250104T000000, start_date=20250115T153329, end_date=20250115T153433
[2025-01-15T15:34:33.942+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task unpack_to_raw (Task received SIGTERM signal; 238)
[2025-01-15T15:34:34.189+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=246, status='terminated', started='15:33:41') (246) terminated with exit code None
[2025-01-15T15:34:34.231+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=238, status='terminated', exitcode=1, started='15:33:28') (238) terminated with exit code 1
[2025-01-15T15:34:34.251+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2025-01-15T15:34:35.301+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
