[2025-01-08T12:58:56.365+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T12:58:56.371+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T12:58:56.371+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-01-08T12:58:56.380+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-01 00:00:00+00:00
[2025-01-08T12:58:56.385+0000] {standard_task_runner.py:57} INFO - Started process 285 to run task
[2025-01-08T12:58:56.389+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpt53ppth9']
[2025-01-08T12:58:56.392+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask unpack_to_raw
[2025-01-08T12:58:56.409+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T12:58:56.452+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [running]> on host 1b6611c57a45
[2025-01-08T12:58:56.506+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-01-08T12:58:56.507+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T12:58:56.508+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-08T12:58:56.515+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T12:58:56.675+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-08T12:58:56.679+0000] {subprocess.py:93} INFO -   File "/opt/***/build/unpack_to_raw.py", line 3, in <module>
[2025-01-08T12:58:56.679+0000] {subprocess.py:93} INFO -     from datasets import load_dataset
[2025-01-08T12:58:56.679+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'datasets'
[2025-01-08T12:58:56.679+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-08T12:58:56.687+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-08T12:58:56.689+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250101T000000, start_date=20250108T125856, end_date=20250108T125856
[2025-01-08T12:58:56.698+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task unpack_to_raw (Bash command failed. The command returned a non-zero exit code 1.; 285)
[2025-01-08T12:58:56.742+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-08T12:58:56.762+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-08T13:04:31.218+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T13:04:31.223+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T13:04:31.224+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-01-08T13:04:31.232+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-01 00:00:00+00:00
[2025-01-08T13:04:31.236+0000] {standard_task_runner.py:57} INFO - Started process 346 to run task
[2025-01-08T13:04:31.238+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpb001asc0']
[2025-01-08T13:04:31.241+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask unpack_to_raw
[2025-01-08T13:04:31.252+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T13:04:31.274+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [running]> on host 1b6611c57a45
[2025-01-08T13:04:31.323+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-01-08T13:04:31.324+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T13:04:31.324+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-08T13:04:31.330+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T13:04:31.480+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-08T13:04:31.480+0000] {subprocess.py:93} INFO -   File "/opt/***/build/unpack_to_raw.py", line 3, in <module>
[2025-01-08T13:04:31.480+0000] {subprocess.py:93} INFO -     from datasets import load_dataset
[2025-01-08T13:04:31.481+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'datasets'
[2025-01-08T13:04:31.483+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-08T13:04:31.491+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-08T13:04:31.493+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250101T000000, start_date=20250108T130431, end_date=20250108T130431
[2025-01-08T13:04:31.502+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task unpack_to_raw (Bash command failed. The command returned a non-zero exit code 1.; 346)
[2025-01-08T13:04:31.541+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-08T13:04:31.558+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-08T13:17:16.238+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T13:17:16.249+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T13:17:16.250+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-01-08T13:17:16.266+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-01 00:00:00+00:00
[2025-01-08T13:17:16.270+0000] {standard_task_runner.py:57} INFO - Started process 183 to run task
[2025-01-08T13:17:16.273+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp8rp5lfr7']
[2025-01-08T13:17:16.277+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask unpack_to_raw
[2025-01-08T13:17:16.289+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T13:17:16.311+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [running]> on host 1b6611c57a45
[2025-01-08T13:17:16.385+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-01-08T13:17:16.399+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T13:17:16.400+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-08T13:17:16.408+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T13:17:16.731+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-08T13:17:16.733+0000] {subprocess.py:93} INFO -   File "/opt/***/build/unpack_to_raw.py", line 3, in <module>
[2025-01-08T13:17:16.733+0000] {subprocess.py:93} INFO -     from datasets import load_dataset
[2025-01-08T13:17:16.734+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'datasets'
[2025-01-08T13:17:16.740+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-08T13:17:16.758+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-08T13:17:16.763+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250101T000000, start_date=20250108T131716, end_date=20250108T131716
[2025-01-08T13:17:16.779+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task unpack_to_raw (Bash command failed. The command returned a non-zero exit code 1.; 183)
[2025-01-08T13:17:16.823+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-08T13:17:16.850+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
