[2025-01-08T12:53:53.218+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T12:53:53.230+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T12:53:53.233+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T12:53:53.257+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-01 00:00:00+00:00
[2025-01-08T12:53:53.271+0000] {standard_task_runner.py:57} INFO - Started process 213 to run task
[2025-01-08T12:53:53.274+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmphcihcs52']
[2025-01-08T12:53:53.283+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask unpack_to_raw
[2025-01-08T12:53:53.339+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T12:53:53.504+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [running]> on host 1b6611c57a45
[2025-01-08T12:53:53.935+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-01-08T12:53:53.964+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T12:53:53.966+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-08T12:53:53.988+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T12:53:54.517+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-08T12:53:54.521+0000] {subprocess.py:93} INFO -   File "/opt/***/build/unpack_to_raw.py", line 3, in <module>
[2025-01-08T12:53:54.524+0000] {subprocess.py:93} INFO -     from datasets import load_dataset
[2025-01-08T12:53:54.527+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'datasets'
[2025-01-08T12:53:54.531+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-08T12:53:54.571+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-08T12:53:54.579+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250101T000000, start_date=20250108T125353, end_date=20250108T125354
[2025-01-08T12:53:54.640+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task unpack_to_raw (Bash command failed. The command returned a non-zero exit code 1.; 213)
[2025-01-08T12:53:54.667+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-08T12:53:54.750+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-08T12:59:29.780+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T12:59:29.786+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T12:59:29.786+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T12:59:29.795+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-01 00:00:00+00:00
[2025-01-08T12:59:29.800+0000] {standard_task_runner.py:57} INFO - Started process 293 to run task
[2025-01-08T12:59:29.803+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp7rc7jq4_']
[2025-01-08T12:59:29.805+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask unpack_to_raw
[2025-01-08T12:59:29.821+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T12:59:29.854+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [running]> on host 1b6611c57a45
[2025-01-08T12:59:29.921+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-01-08T12:59:29.923+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T12:59:29.924+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-08T12:59:29.931+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T12:59:30.078+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-08T12:59:30.078+0000] {subprocess.py:93} INFO -   File "/opt/***/build/unpack_to_raw.py", line 3, in <module>
[2025-01-08T12:59:30.078+0000] {subprocess.py:93} INFO -     from datasets import load_dataset
[2025-01-08T12:59:30.079+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'datasets'
[2025-01-08T12:59:30.081+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-08T12:59:30.089+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-08T12:59:30.093+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250101T000000, start_date=20250108T125929, end_date=20250108T125930
[2025-01-08T12:59:30.100+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task unpack_to_raw (Bash command failed. The command returned a non-zero exit code 1.; 293)
[2025-01-08T12:59:30.108+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-08T12:59:30.126+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-08T13:08:47.402+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T13:08:47.409+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T13:08:47.409+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T13:08:47.418+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-01 00:00:00+00:00
[2025-01-08T13:08:47.422+0000] {standard_task_runner.py:57} INFO - Started process 394 to run task
[2025-01-08T13:08:47.425+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpomngoz23']
[2025-01-08T13:08:47.427+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask unpack_to_raw
[2025-01-08T13:08:47.438+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T13:08:47.460+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [running]> on host 1b6611c57a45
[2025-01-08T13:08:47.512+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-01-08T13:08:47.513+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T13:08:47.514+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-08T13:08:47.520+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T13:08:47.687+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-08T13:08:47.687+0000] {subprocess.py:93} INFO -   File "/opt/***/build/unpack_to_raw.py", line 3, in <module>
[2025-01-08T13:08:47.688+0000] {subprocess.py:93} INFO -     from datasets import load_dataset
[2025-01-08T13:08:47.688+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'datasets'
[2025-01-08T13:08:47.690+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-08T13:08:47.699+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-08T13:08:47.703+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250101T000000, start_date=20250108T130847, end_date=20250108T130847
[2025-01-08T13:08:47.710+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task unpack_to_raw (Bash command failed. The command returned a non-zero exit code 1.; 394)
[2025-01-08T13:08:47.730+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-08T13:08:47.750+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-08T13:12:13.746+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T13:12:13.753+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T13:12:13.753+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T13:12:13.761+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-01 00:00:00+00:00
[2025-01-08T13:12:13.764+0000] {standard_task_runner.py:57} INFO - Started process 432 to run task
[2025-01-08T13:12:13.767+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpam73hgw3']
[2025-01-08T13:12:13.770+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask unpack_to_raw
[2025-01-08T13:12:13.793+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T13:12:13.821+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [running]> on host 1b6611c57a45
[2025-01-08T13:12:13.867+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-01-08T13:12:13.868+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T13:12:13.868+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-08T13:12:13.874+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T13:12:14.018+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-08T13:12:14.018+0000] {subprocess.py:93} INFO -   File "/opt/***/build/unpack_to_raw.py", line 3, in <module>
[2025-01-08T13:12:14.018+0000] {subprocess.py:93} INFO -     from datasets import load_dataset
[2025-01-08T13:12:14.019+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'datasets'
[2025-01-08T13:12:14.021+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-08T13:12:14.028+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-08T13:12:14.032+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250101T000000, start_date=20250108T131213, end_date=20250108T131214
[2025-01-08T13:12:14.039+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task unpack_to_raw (Bash command failed. The command returned a non-zero exit code 1.; 432)
[2025-01-08T13:12:14.071+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-08T13:12:14.098+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-08T13:30:51.791+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T13:30:51.798+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T13:30:51.799+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T13:30:51.806+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-01 00:00:00+00:00
[2025-01-08T13:30:51.811+0000] {standard_task_runner.py:57} INFO - Started process 178 to run task
[2025-01-08T13:30:51.814+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpnurdtwpo']
[2025-01-08T13:30:51.815+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask unpack_to_raw
[2025-01-08T13:30:51.825+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T13:30:51.853+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [running]> on host 8105279881a3
[2025-01-08T13:30:51.922+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-01-08T13:30:51.924+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T13:30:51.925+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-08T13:30:51.931+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T13:31:01.884+0000] {subprocess.py:93} INFO - Téléchargement des données...
[2025-01-08T13:31:01.950+0000] {subprocess.py:93} INFO - Generating test split:   0%|          | 0/4358 [00:00<?, ? examples/s]Generating test split: 100%|██████████| 4358/4358 [00:00<00:00, 72672.10 examples/s]
[2025-01-08T13:31:02.028+0000] {subprocess.py:93} INFO - Generating train split:   0%|          | 0/36718 [00:00<?, ? examples/s]Generating train split: 100%|██████████| 36718/36718 [00:00<00:00, 480549.35 examples/s]
[2025-01-08T13:31:04.484+0000] {subprocess.py:93} INFO - Generating validation split:   0%|          | 0/3760 [00:00<?, ? examples/s]Generating validation split: 100%|██████████| 3760/3760 [00:00<00:00, 505953.90 examples/s]
[2025-01-08T13:31:04.485+0000] {subprocess.py:93} INFO - Données téléchargées et organisées.
[2025-01-08T13:31:04.486+0000] {subprocess.py:93} INFO - Combinaison et téléversement des fichiers...
[2025-01-08T13:31:04.486+0000] {subprocess.py:93} INFO - Erreur lors du téléversement : Unable to locate credentials
[2025-01-08T13:31:04.486+0000] {subprocess.py:93} INFO - Traitement terminé.
[2025-01-08T13:31:04.673+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-08T13:31:04.738+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250101T000000, start_date=20250108T133051, end_date=20250108T133104
[2025-01-08T13:31:04.791+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-08T13:31:04.820+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
