[2025-01-08T13:32:21.700+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_curated manual__2025-01-08T13:30:48.302371+00:00 [queued]>
[2025-01-08T13:32:21.707+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_curated manual__2025-01-08T13:30:48.302371+00:00 [queued]>
[2025-01-08T13:32:21.707+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T13:32:21.715+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_to_curated> on 2025-01-08 13:30:48.302371+00:00
[2025-01-08T13:32:21.718+0000] {standard_task_runner.py:57} INFO - Started process 678 to run task
[2025-01-08T13:32:21.721+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'process_to_curated', 'manual__2025-01-08T13:30:48.302371+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpd8gt8urb']
[2025-01-08T13:32:21.723+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask process_to_curated
[2025-01-08T13:32:21.733+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T13:32:21.752+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.process_to_curated manual__2025-01-08T13:30:48.302371+00:00 [running]> on host 8105279881a3
[2025-01-08T13:32:21.798+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='process_to_curated' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T13:30:48.302371+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-08T13:30:48.302371+00:00'
[2025-01-08T13:32:21.799+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T13:32:21.800+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/scripts/process_to_curated.py --mysql_host mysql --mysql_user root --mysql_password root --mongo_uri mongodb://mongodb:27017/']
[2025-01-08T13:32:21.805+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T13:32:22.756+0000] {subprocess.py:93} INFO - None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[2025-01-08T13:32:23.292+0000] {subprocess.py:93} INFO - /opt/***/scripts/process_to_curated.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-01-08T13:32:23.293+0000] {subprocess.py:93} INFO -   df = pd.read_sql(query, connection)
[2025-01-08T13:32:23.293+0000] {subprocess.py:93} INFO - Récupération des données depuis MySQL...
[2025-01-08T13:32:23.293+0000] {subprocess.py:93} INFO - Erreur lors de la récupération des données MySQL: Execution failed on sql 'SELECT id, text FROM texts': 1146 (42S02): Table 'staging.texts' doesn't exist
[2025-01-08T13:32:23.294+0000] {subprocess.py:93} INFO - Aucune donnée récupérée depuis MySQL
[2025-01-08T13:32:23.422+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-08T13:32:23.457+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=process_to_curated, execution_date=20250108T133048, start_date=20250108T133221, end_date=20250108T133223
[2025-01-08T13:32:23.486+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-08T13:32:23.503+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
