[2025-01-15T15:33:29.316+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-01-15T15:33:29.381+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-01-15T15:33:29.383+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-15T15:33:29.614+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-08 00:00:00+00:00
[2025-01-15T15:33:29.786+0000] {standard_task_runner.py:57} INFO - Started process 245 to run task
[2025-01-15T15:33:29.822+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-08T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/wikitext_dag.py', '--cfg-path', '/tmp/tmpyw1zgne5']
[2025-01-15T15:33:29.847+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask unpack_to_raw
[2025-01-15T15:33:30.314+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-15T15:33:31.303+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-08T00:00:00+00:00 [running]> on host 9159fb56fd7e
[2025-01-15T15:33:42.413+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-08T00:00:00+00:00'
[2025-01-15T15:33:42.678+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-15T15:33:42.727+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-15T15:33:42.904+0000] {subprocess.py:86} INFO - Output:
[2025-01-15T15:34:30.000+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2025-01-15T15:34:30.640+0000] {process_utils.py:131} INFO - Sending 15 to group 245. PIDs of all processes in the group: [250, 245]
[2025-01-15T15:34:30.763+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 245
[2025-01-15T15:34:31.383+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-15T15:34:32.469+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-01-15T15:34:33.297+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-01-15T15:34:33.546+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250108T000000, start_date=20250115T153329, end_date=20250115T153433
[2025-01-15T15:34:34.076+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task unpack_to_raw (Task received SIGTERM signal; 245)
[2025-01-15T15:34:34.212+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=245, status='terminated', exitcode=1, started='15:33:28') (245) terminated with exit code 1
[2025-01-15T15:34:34.245+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=250, status='terminated', started='15:33:41') (250) terminated with exit code None
[2025-01-15T15:34:34.278+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2025-01-15T15:34:35.368+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
