[2025-01-08T12:53:55.705+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw manual__2025-01-08T12:53:50.799139+00:00 [queued]>
[2025-01-08T12:53:55.711+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw manual__2025-01-08T12:53:50.799139+00:00 [queued]>
[2025-01-08T12:53:55.711+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T12:53:55.720+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-08 12:53:50.799139+00:00
[2025-01-08T12:53:55.727+0000] {standard_task_runner.py:57} INFO - Started process 224 to run task
[2025-01-08T12:53:55.730+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'manual__2025-01-08T12:53:50.799139+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp4p1rea1v']
[2025-01-08T12:53:55.732+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask unpack_to_raw
[2025-01-08T12:53:55.746+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T12:53:55.771+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw manual__2025-01-08T12:53:50.799139+00:00 [running]> on host 1b6611c57a45
[2025-01-08T12:53:55.821+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T12:53:50.799139+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-08T12:53:50.799139+00:00'
[2025-01-08T12:53:55.824+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T12:53:55.825+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-08T12:53:55.830+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T12:53:55.978+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-08T12:53:55.978+0000] {subprocess.py:93} INFO -   File "/opt/***/build/unpack_to_raw.py", line 3, in <module>
[2025-01-08T12:53:55.979+0000] {subprocess.py:93} INFO -     from datasets import load_dataset
[2025-01-08T12:53:55.979+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'datasets'
[2025-01-08T12:53:55.981+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-08T12:53:55.989+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-08T12:53:55.992+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250108T125350, start_date=20250108T125355, end_date=20250108T125355
[2025-01-08T12:53:56.001+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task unpack_to_raw (Bash command failed. The command returned a non-zero exit code 1.; 224)
[2025-01-08T12:53:56.035+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-08T12:53:56.051+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
