[2025-01-15T15:33:28.737+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-03T00:00:00+00:00 [queued]>
[2025-01-15T15:33:29.290+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-03T00:00:00+00:00 [queued]>
[2025-01-15T15:33:29.293+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-15T15:33:29.498+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-03 00:00:00+00:00
[2025-01-15T15:33:29.604+0000] {standard_task_runner.py:57} INFO - Started process 240 to run task
[2025-01-15T15:33:30.028+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-03T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/wikitext_dag.py', '--cfg-path', '/tmp/tmp_5dv4szb']
[2025-01-15T15:33:30.109+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask unpack_to_raw
[2025-01-15T15:33:30.594+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-15T15:33:32.038+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-03T00:00:00+00:00 [running]> on host 9159fb56fd7e
[2025-01-15T15:33:43.611+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-03T00:00:00+00:00'
[2025-01-15T15:33:43.912+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-15T15:33:43.922+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-15T15:33:44.022+0000] {subprocess.py:86} INFO - Output:
[2025-01-15T15:34:30.094+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2025-01-15T15:34:30.626+0000] {process_utils.py:131} INFO - Sending 15 to group 240. PIDs of all processes in the group: [256, 240]
[2025-01-15T15:34:30.738+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 240
[2025-01-15T15:34:31.533+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-15T15:34:32.475+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-01-15T15:34:33.539+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-01-15T15:34:33.789+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250103T000000, start_date=20250115T153329, end_date=20250115T153433
[2025-01-15T15:34:34.668+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task unpack_to_raw (Task received SIGTERM signal; 240)
[2025-01-15T15:34:34.735+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=256, status='terminated', started='15:33:42') (256) terminated with exit code None
[2025-01-15T15:34:34.761+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=240, status='terminated', exitcode=1, started='15:33:28') (240) terminated with exit code 1
[2025-01-15T15:34:34.795+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2025-01-15T15:34:36.063+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
