[2025-01-15T15:33:28.849+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-14T00:00:00+00:00 [queued]>
[2025-01-15T15:33:29.279+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-14T00:00:00+00:00 [queued]>
[2025-01-15T15:33:29.282+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-15T15:33:29.409+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-14 00:00:00+00:00
[2025-01-15T15:33:29.589+0000] {standard_task_runner.py:57} INFO - Started process 236 to run task
[2025-01-15T15:33:29.847+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-14T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/wikitext_dag.py', '--cfg-path', '/tmp/tmpgb9vh6er']
[2025-01-15T15:33:29.955+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask unpack_to_raw
[2025-01-15T15:33:30.202+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-15T15:33:31.247+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-14T00:00:00+00:00 [running]> on host 9159fb56fd7e
[2025-01-15T15:33:42.395+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-14T00:00:00+00:00'
[2025-01-15T15:33:42.680+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-15T15:33:42.729+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-15T15:33:42.916+0000] {subprocess.py:86} INFO - Output:
[2025-01-15T15:34:29.883+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2025-01-15T15:34:30.424+0000] {process_utils.py:131} INFO - Sending 15 to group 236. PIDs of all processes in the group: [249, 236]
[2025-01-15T15:34:30.472+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 236
[2025-01-15T15:34:30.663+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-15T15:34:31.237+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-01-15T15:34:32.856+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-01-15T15:34:33.175+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250114T000000, start_date=20250115T153329, end_date=20250115T153433
[2025-01-15T15:34:33.691+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task unpack_to_raw (Task received SIGTERM signal; 236)
[2025-01-15T15:34:33.839+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=249, status='terminated', started='15:33:41') (249) terminated with exit code None
[2025-01-15T15:34:33.886+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=236, status='terminated', exitcode=1, started='15:33:28') (236) terminated with exit code 1
[2025-01-15T15:34:33.923+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2025-01-15T15:34:35.112+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
